sonar.projectKey=angular-front
sonar.projectName=angular-front
sonar.host.url=http://localhost:9000
sonar.token=squ_5d8d14fbf3c2d9589f4a10820e48054cc9db79a7

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/environments/**,src/assets/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.coverage.exclusions=src/environments/**,src/main.ts,src/main.server.ts,src/server.ts,src/app/app.config.ts,src/app/app.config.server.ts,**/*.module.ts,**/*route*.ts,**/interfaces/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info